backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "pages"
    label: "Pages"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/pages/landing-page.md"
        label: "Landing Page"
        name: "landing-page"
        fields:
          - {label: Main title strapline, name: _1_strapline, widget: string, required: true}
          - {label: Lead paragraph, name: _2_paragraph_1, widget: markdown, required: true}
          - {label: 1st subtitle, name: _3_sub_title, widget: string, required: true}
          - {label: 1st paragraph, name: _4_paragraph_2, widget: markdown, required: true}
          - {label: 2nd subtitle, name: _5_sub_title_2, widget: string, required: true}
          - {label: 2nd paragraph, name: _6_paragraph_3, widget: markdown, required: true}
      - file: "content/pages/00-start.md"
        label: "Tool start page"
        name: "00-start"
        fields:
          - {label: Title, name: title, widget: string, required: true}
          - {label: Top content, name: top_content, widget: markdown, required: true}
          - {label: Block one title, name: block_one_title, widget: string, required: true}
          - {label: Block one content, name: block_one_content, widget: string, required: true}
          - {label: Block two title, name: block_two_title, widget: string, required: true}
          - {label: Block two content, name: block_two_content, widget: string, required: true}
          - {label: Block three title, name: block_three_title, widget: string, required: true}
          - {label: Block three content, name: block_three_content, widget: string, required: true}
          - {label: Bottom content, name: bottom_content, widget: markdown, required: true}
      - file: "content/pages/01-strong-skills.md"
        label: "Tool Step 1 - strong skills"
        name: "01-strong-skills"
        fields:
          - {label: Content, name: body, widget: markdown}
      - file: "content/pages/02-weak-skills.md"
        label: "Tool Step 2 - weak skills"
        name: "02-weak-skills"
        fields:
          - {label: Content, name: body, widget: markdown}
      - file: "content/pages/03-strong-attitudes.md"
        label: "Tool Step 3 - strong attitudes"
        name: "03-strong-attitudes"
        fields:
          - {label: Content, name: body, widget: markdown}
      - file: "content/pages/04-weak-attitudes.md"
        label: "Tool Step 4 - weak attitudes"
        name: "04-weak-attitudes.md"
        fields:
          - {label: Content, name: body, widget: markdown}
      - file: "content/pages/05-sign-up.md"
        label: "Tool Step 5 - sign up"
        name: "05-sign-up"
        fields:
          - {label: Title, name: title, widget: string, required: true}
          - {label: Content, name: body, widget: markdown}
      - file: "content/pages/06-results.md"
        label: "Results"
        name: "06-results"
        fields:
          - {label: Title, name: title, widget: string, required: true}
          - {label: Content, name: body, widget: markdown}
          - {label: No account Title, name: not_signed_up_title, widget: string, hint: This text will only be displayed to a user who has chosen not to sign up with an account }
          - {label: No account Text, name: not_signed_up_body, widget: string}
          - {label: Your Skills Title, name: title_2, widget: string}
          - {label: Your Skills Content, name: body_2, widget: markdown}
          - {label: What next Title, name: title_3, widget: string}
          - {label: What next Content, name: body_3, widget: markdown}
          - {label: Team activites Title, name: title_4, widget: string}
          - {label: Team activites Content, name: body_4, widget: markdown}
          - {label: Develop skills Title, name: title_5, widget: string}
          - {label: Develop skills Content, name: body_5, widget: markdown}
          - {label: Downloads Title, name: title_6, widget: string}
          - {label: Downloads Content, name: body_6, widget: markdown}
          - {label: Competency Framework PDF, name: pdf_1, widget: file}
          - {label: Practice Guide PDF, name: pdf_2, widget: file}
          - {label: Contact us Title, name: title_7, widget: string}
          - {label: contact us Content, name: body_7, widget: markdown}
      - file: "content/pages/07-results-team-activites.md"
        label: "Results - team activites"
        name: "07-results-team-activites"
        fields:
          - {label: Title, name: title, widget: string, required: true}
          - {label: PDF download, name: pdf, widget: file}
          - {label: Content, name: body, widget: markdown}
      - file: "content/pages/08-results-skills-development.md"
        label: "Results - skills development"
        name: "08-results-skills-development"
        fields:
          - {label: Title, name: title, widget: string, required: true}
          - {label: Content, name: body, widget: markdown}      

  - name: skills
    label: Skills
    editor:
      preview: false
    folder: content/skills
    slug: "{{slug}}"
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - {label: id, name: id, widget: hidden}
      - {label: Brand, name: brand, widget: string}
      - {label: text, name: text, widget: text}
      - {label: Content, name: body, widget: markdown}
      - label: Resources - Read
        name: read 
        widget: list
        fields: 
          - {label: Resource text, name: text, widget: string, required: true }
          - {label: Resource URL, name: url, widget: string }
      - label: Resources - Watch
        name: watch 
        widget: list
        fields: 
          - {label: Resource text, name: text, widget: string, required: true }
          - {label: Resource URL, name: url, widget: string }
      - label: Resources - Use
        name: use 
        widget: list
        fields: 
          - {label: Resource text, name: text, widget: string, required: true }
          - {label: Resource URL, name: url, widget: string }

  - name: roles
    label: Roles
    editor:
      preview: false
    folder: content/roles
    slug: "{{slug}}"
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - {label: Sub title, name: sub_title, widget: string}
      - {label: id, name: id, widget: hidden}
      - {label: Action, name: action, widget: string}
      - {label: Content, name: body, widget: markdown}
      - {label: Brand, name: brand, widget: select, options: ["working_together", "learning", "leading_change"] }
      - label: Competencies
        name: competencies 
        widget: list
        fields: 
          - {label: "Competency text", name: text, widget: string }
          - {label: "Competency brand", name: brand, widget: select, options: ["working_together", "learning", "leading_change"] }
      - label: Role Strengths
        name: strengths 
        widget: list
        fields: 
          - {label: Strength, name: text, widget: string }
      - label: Role Weaknesses
        name: weaknesses 
        widget: list
        fields: 
          - {label: Weakness, name: text, widget: string }
      - label: Role Attitudes
        name: attitudes 
        widget: list
        fields: 
          - {label: Attitude, name: text, widget: string }
      - {label: Attitudes, name: attitudesMapping, widget: hidden}
      - {label: Skills, name: skillsMapping, widget: hidden}
      - {label: Sub Skills, name: subSkillsMapping, widget: hidden}

  - name: attitudes
    label: Attitudes
    editor:
      preview: false
    folder: content/attitudes
    slug: "{{slug}}"
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - {label: id, name: id, widget: hidden}
      - {label: Brand, name: brand, widget: string}
      - {label: Text, name: text, widget: string}