backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "pages"
    label: "Page"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/pages/landing-page.md"
        label: "Landing Page"
        name: "landing-page"
        fields:
          - {label: _1_strapline, name: _1_strapline, widget: string, required: true}
          - {label: _2_paragraph_1, name: _2_paragraph_1, widget: markdown, required: true}
          - {label: _3_sub_title, name: _3_sub_title, widget: string, required: true}
          - {label: _4_paragraph_2, name: _4_paragraph_2, widget: markdown, required: true}
          - {label: _5_sub_title_2, name: _5_sub_title_2, widget: string, required: true}
      - file: "content/pages/00-start.md"
        label: "Start page"
        name: "00-start"
        fields:
          - {label: Title, name: title, widget: string, required: true}
          - {label: Top content, name: top_content, widget: markdown, required: true}
          - {label: Block one title, name: block_one_title, widget: string, required: true}
          - {label: Block one content, name: block_one_content, widget: string, required: true}
          - {label: Block two title, name: block_two_title, widget: string, required: true}
          - {label: Block two content, name: block_two_content, widget: string, required: true}
          - {label: Block three title, name: block_three_title, widget: string, required: true}
          - {label: Block three content, name: block_three_content, widget: string, required: true}
          - {label: Bottom content, name: bottom_content, widget: markdown, required: true}
      - file: "content/pages/01-strong-skills.md"
        label: "Tool Step 1"
        name: "01-strong-skills"
        fields:
          - {label: Content, name: body, widget: markdown}
      - file: "content/pages/02-weak-skills.md"
        label: "Tool Step 2"
        name: "02-weak-skills"
        fields:
          - {label: Content, name: body, widget: markdown}
      - file: "content/pages/03-strong-attitudes.md"
        label: "Tool Step 3"
        name: "03-strong-attitudes"
        fields:
          - {label: Content, name: body, widget: markdown}
      - file: "content/pages/04-weak-attitudes.md"
        label: "Tool Step 4"
        name: "04-weak-attitudes.md"
        fields:
          - {label: Content, name: body, widget: markdown}
      - file: "content/pages/05-sign-up.md"
        label: "Tool Step 5"
        name: "05-sign-up"
        fields:
          - {label: Title, name: title, widget: string, required: true}
          - {label: Content, name: body, widget: markdown}

  - name: skills
    label: Skill
    editor:
      preview: false
    folder: content/skills
    slug: "{{slug}}"
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - {label: id, name: id, widget: hidden}
      - {label: Brand, name: brand, widget: string}
      - {label: text, name: text, widget: text}
      - {label: Content, name: body, widget: markdown}


  - name: roles
    label: Roles
    editor:
      preview: false
    folder: content/roles
    slug: "{{slug}}"
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - {label: Sub title, name: sub_title, widget: string}
      - {label: id, name: id, widget: hidden}
      - {label: Action, name: action, widget: string}
      - {label: Attitudes, name: attitudesMapping, widget: hidden}
      - {label: Skills, name: skillsMapping, widget: hidden}
      - {label: Sub Skills, name: subSkillsMapping, widget: hidden}
      - {label: Content, name: body, widget: string}

  - name: attitudes
    label: Attitudes
    editor:
      preview: false
    folder: content/attitudes
    slug: "{{slug}}"
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - {label: id, name: id, widget: hidden}
      - {label: Brand, name: brand, widget: string}
      - {label: Text, name: text, widget: string}